"""
AskERP — Export Engine
=================================
Generates PDF and Excel files from AI chat data on the server side.
Files are saved as Frappe file attachments and returned as download URLs.

Endpoints:
  POST /api/method/askerp.exports.export_pdf   — Generate PDF from chat content
  POST /api/method/askerp.exports.export_excel  — Generate Excel from table data
"""

import json
import frappe
from frappe import _
from frappe.utils import get_site_url
from askerp.formatting import get_trading_name, get_report_filename_prefix, get_cached_profile


def _check_access():
    """
    Verify user has AI chat access.

    Bootstrap-safe: checks if allow_ai_chat field exists before querying.
    On fresh install, the field may not exist yet (created by after_install hook).
    """
    user = frappe.session.user
    if user == "Administrator":
        return True
    # Bootstrap protection: skip check if custom field doesn't exist yet
    if not frappe.db.has_column("User", "allow_ai_chat"):
        frappe.throw(_("AI system is still being set up. Please try again shortly."), frappe.PermissionError)
    allow = frappe.db.get_value("User", user, "allow_ai_chat")
    if not allow:
        frappe.throw(_("AI Chat access required for exports."), frappe.PermissionError)
    return True


@frappe.whitelist()
def export_pdf(title, content, session_id=None):
    """
    Generate a PDF from AI chat content (markdown/HTML).

    Args:
        title (str): Report title
        content (str): Markdown or HTML content from AI response
        session_id (str): Chat session reference

    Returns:
        dict: {file_url, file_name}
    """
    _check_access()

    from frappe.utils.pdf import get_pdf
    import re

    # Convert markdown-style tables to HTML tables
    html_content = _markdown_to_html(content)

    # Build styled HTML document
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                font-size: 11pt;
                color: #1a1a1a;
                line-height: 1.6;
                padding: 20px;
            }}
            .header {{
                border-bottom: 3px solid #056839;
                padding-bottom: 12px;
                margin-bottom: 20px;
            }}
            .header h1 {{
                color: #143121;
                font-size: 18pt;
                margin: 0;
            }}
            .header .subtitle {{
                color: #666;
                font-size: 10pt;
                margin-top: 4px;
            }}
            .header .logo {{
                color: #056839;
                font-weight: 700;
                font-size: 10pt;
            }}
            table {{
                border-collapse: collapse;
                width: 100%;
                margin: 12px 0;
                font-size: 10pt;
            }}
            th {{
                background-color: #056839;
                color: white;
                padding: 8px 12px;
                text-align: left;
                font-weight: 600;
            }}
            td {{
                padding: 6px 12px;
                border-bottom: 1px solid #e0e0e0;
            }}
            tr:nth-child(even) {{
                background-color: #f8f8f8;
            }}
            h2 {{
                color: #143121;
                font-size: 14pt;
                margin-top: 20px;
                border-bottom: 1px solid #e0e0e0;
                padding-bottom: 4px;
            }}
            h3 {{
                color: #056839;
                font-size: 12pt;
                margin-top: 16px;
            }}
            strong {{
                color: #143121;
            }}
            .footer {{
                margin-top: 30px;
                padding-top: 10px;
                border-top: 1px solid #e0e0e0;
                font-size: 9pt;
                color: #999;
                text-align: center;
            }}
        </style>
    </head>
    <body>
        <div class="header">
            <span class="logo">{_escape_html(get_trading_name().upper())}</span>
            <h1>{_escape_html(title)}</h1>
            <div class="subtitle">
                Generated by AskERP on {frappe.utils.format_datetime(frappe.utils.now_datetime(), "dd MMM yyyy, hh:mm a")}
            </div>
        </div>

        <div class="content">
            {html_content}
        </div>

        <div class="footer">
            AskERP — AI-Generated Report
        </div>
    </body>
    </html>
    """

    # Generate PDF bytes
    pdf_data = get_pdf(html, options={
        "page-size": "A4",
        "margin-top": "15mm",
        "margin-right": "15mm",
        "margin-bottom": "15mm",
        "margin-left": "15mm",
    })

    # Save as Frappe file
    file_name = f"{get_report_filename_prefix()}_{frappe.utils.now_datetime().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_doc = frappe.get_doc({
        "doctype": "File",
        "file_name": file_name,
        "content": pdf_data,
        "is_private": 1,
        "attached_to_doctype": "AI Chat Session" if session_id else None,
        "attached_to_name": session_id,
    })
    file_doc.save(ignore_permissions=True)
    frappe.db.commit()

    return {
        "file_url": file_doc.file_url,
        "file_name": file_name,
        "download_url": f"{get_site_url(frappe.local.site)}{file_doc.file_url}",
    }


@frappe.whitelist()
def export_excel(title, data, columns=None, session_id=None):
    """
    Generate an Excel file from structured data.

    Args:
        title (str): Sheet/report title
        data (str): JSON-encoded list of dicts (rows)
        columns (str, optional): JSON-encoded list of column definitions
        session_id (str): Chat session reference

    Returns:
        dict: {file_url, file_name}
    """
    _check_access()

    import io

    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    except ImportError:
        frappe.throw("openpyxl is required for Excel export. Run: pip install openpyxl")

    # Parse inputs
    if isinstance(data, str):
        data = json.loads(data)
    if isinstance(columns, str) and columns:
        columns = json.loads(columns)

    if not data:
        frappe.throw("No data to export.")

    # Auto-detect columns from data keys if not provided
    if not columns:
        columns = list(data[0].keys())

    wb = Workbook()
    ws = wb.active
    ws.title = title[:31]  # Excel sheet name max 31 chars

    # Styles
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="056839", end_color="056839", fill_type="solid")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell_font = Font(name="Calibri", size=10)
    cell_border = Border(bottom=Side(style="thin", color="E0E0E0"))

    # Number format based on business profile setting
    profile = get_cached_profile()
    num_format = profile.get("number_format", "Indian (Lakhs, Crores)")
    if "Indian" in num_format:
        number_format_str = '#,##,##0.00'     # Indian: 1,23,456.78
    elif "International" in num_format:
        number_format_str = '#,##0.00'         # International: 123,456.78
    else:
        number_format_str = '0.00'             # Plain: 123456.78

    # Title row
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(columns))
    title_cell = ws.cell(row=1, column=1, value=title)
    title_cell.font = Font(name="Calibri", size=14, bold=True, color="143121")
    title_cell.alignment = Alignment(horizontal="left")

    # Subtitle row
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=len(columns))
    sub_cell = ws.cell(row=2, column=1,
                       value=f"Generated by AskERP on {frappe.utils.now_datetime().strftime('%d %b %Y, %I:%M %p')}")
    sub_cell.font = Font(name="Calibri", size=9, italic=True, color="999999")

    # Header row (row 4)
    for col_idx, col_name in enumerate(columns, 1):
        cell = ws.cell(row=4, column=col_idx, value=_format_column_name(col_name))
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align

    # Data rows
    for row_idx, row in enumerate(data, 5):
        for col_idx, col_name in enumerate(columns, 1):
            value = row.get(col_name, "")
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            cell.font = cell_font
            cell.border = cell_border

            # Auto-format numbers
            if isinstance(value, (int, float)):
                cell.number_format = number_format_str if abs(value) >= 1000 else '0.00'
                cell.alignment = Alignment(horizontal="right")

    # Auto-size columns
    for col_idx in range(1, len(columns) + 1):
        max_width = max(
            len(str(ws.cell(row=r, column=col_idx).value or ""))
            for r in range(4, min(len(data) + 5, 50))
        )
        ws.column_dimensions[ws.cell(row=4, column=col_idx).column_letter].width = min(max(max_width + 4, 12), 40)

    # Save to bytes
    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    excel_data = output.getvalue()

    # Save as Frappe file
    file_name = f"{get_report_filename_prefix()}_{frappe.utils.now_datetime().strftime('%Y%m%d_%H%M%S')}.xlsx"
    file_doc = frappe.get_doc({
        "doctype": "File",
        "file_name": file_name,
        "content": excel_data,
        "is_private": 1,
        "attached_to_doctype": "AI Chat Session" if session_id else None,
        "attached_to_name": session_id,
    })
    file_doc.save(ignore_permissions=True)
    frappe.db.commit()

    return {
        "file_url": file_doc.file_url,
        "file_name": file_name,
        "download_url": f"{get_site_url(frappe.local.site)}{file_doc.file_url}",
    }


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _markdown_to_html(text):
    """Convert markdown-style content to basic HTML for PDF rendering."""
    import re

    # Escape HTML first
    text = _escape_html(text)

    # Headers
    text = re.sub(r'^### (.+)$', r'<h3>\1</h3>', text, flags=re.MULTILINE)
    text = re.sub(r'^## (.+)$', r'<h2>\1</h2>', text, flags=re.MULTILINE)

    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)

    # Italic
    text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)

    # Tables (markdown pipe tables)
    lines = text.split('\n')
    result = []
    in_table = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if '|' in stripped and stripped.startswith('|') and stripped.endswith('|'):
            cells = [c.strip() for c in stripped.split('|')[1:-1]]

            # Check if this is a separator row (---|---|---)
            if all(c.replace('-', '').replace(':', '').strip() == '' for c in cells):
                continue

            if not in_table:
                result.append('<table>')
                # First row is header
                result.append('<tr>' + ''.join(f'<th>{c}</th>' for c in cells) + '</tr>')
                in_table = True
            else:
                result.append('<tr>' + ''.join(f'<td>{c}</td>' for c in cells) + '</tr>')
        else:
            if in_table:
                result.append('</table>')
                in_table = False
            # Bullet lists
            if stripped.startswith('- '):
                content = stripped[2:]
                result.append(f'<li>{content}</li>')
            elif stripped == '':
                result.append('<br>')
            else:
                result.append(f'<p>{stripped}</p>')

    if in_table:
        result.append('</table>')

    return '\n'.join(result)


def _escape_html(text):
    """Escape HTML special characters."""
    return (text
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;'))


def _format_column_name(name):
    """Convert field_name to Field Name for Excel headers."""
    return name.replace('_', ' ').replace('.', ' ').title()
